### ISSUE TITLE
Issue importing jitclass from numba

### ISSUE THREAD

**Issue by CharlesCardot** [asche1/PyCrystalField#3]
When I tried running PyCrystalField.py I got hit with an error: "cannot import name 'jitclass' from 'numba' (C:\Users\CC\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\__init__.py)"

I was able to fix it by following the recommendation on this website (https://128mots.com/index.php/en/2021/03/01/cannot-import-name-jitclass-from-numba-opt-conda-lib-python3-7-site-packages-numba-__init__-py/) changing "from numba import jitclass" to "from numba.experimental import jitclass"

**Comment by asche1** [comment]
Fixed in source code.
