### ISSUE TITLE
other magnetic ions

### ISSUE THREAD

**Issue by rpday** [asche1/PyCrystalField#7]
Hello,

thanks for building this project! I have the impression that the set of magnetic ions is limited -- specifically there are only tri-valent rare-earths included. Is it possible to include support for others, e.g. Eu2+?

Thanks!

**Comment by asche1** [comment]
Hi Ryan,

You are right that PyCrystalField's point charge calculator is limited to certain ions---these are the ones where I could find well-defined point charge constants.
In principle you could add this functionality yourself if you can find the proper constants for non-trivalent ions, and I could show you how to insert these into the source code.
That being said, beware: Eu2+ has a quenched orbital moment (electronically equivalent to Gd3+) and therefore has a very minor response to ligand fields. I would not attempt a point charge model for this case.

-Allen

**Comment by rpday** [comment]
Hi Allen, thanks for the reply. That's a good point on the Eu2+ orbital moment, I'll keep this in mind.

Best,
Ryan
